[project]
name = "langchain"
version = "0.1.0"
description = ""
authors = [
    {name = "Jose Pablo Soriano Torres",email = "jpst0002@red.ujaen.es"}
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "langchain-anthropic (>=1.7.2,<2.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "langchain-community (>=0.4.2,<0.5.0)",
    "pypdf (>=6.19.0,<7.0.0)",
    "langchain-chroma (>=1.1.0,<2.0.0)",
    "langchain-huggingface (>=1.2.2,<2.0.0)",
    "langchain-core (>=1.6.3,<2.0.0)",
    "pymupdf (>=1.28.2,<2.0.0)",
    "ipykernel (>=7.3.0,<8.0.0)",
    "unstructured (>=0.27.6,<0.28.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "langchain-text-splitters (>=1.1.2,<2.0.0)",
    "sentence-transformers (>=6.0.1,<7.0.0)",
    "chromadb (>=1.5.9,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
